operations-app:
  contactpoint: "https://ops-bk.sandbox.fynarfin.io"
  username: "mifos"
  password: "password"
  auth:
    enabled: false
    header: "Basic Y2xpZW50Og=="
  endpoints:
    auth: "/oauth/token"
    batch-summary: "/api/v1/batch"
    batch-details: "api/v1/batch/detail"
    batch-transaction: "/api/v1/batch/transactions"

    transfers: "/api/v1/transfers?size=1&page=0"
    transactionRequests: "/api/v1/transactionRequests"

paybill:
  mpesa-connector:
    contactpoint: https://mpesa.sandbox.fynarfin.io
    endpoints:
      validation: "/validation"
      settlement: "/confirmation"

bulk-processor:
  contactpoint: "https://bulk-connector.sandbox.fynarfin.io"
  endpoints:
    bulk-transactions: "/batchtransactions"
    simulate: "/simulate"

channel-connector:
  contactpoint: "https://channel.sandbox.fynarfin.io"
  endpoints:
    transfer: "/channel/transfer"
    gsma-p2p: "/channel/gsma/transfer"
    collection: "/channel/collection"
    transferReq: "/channel/transactionRequest"

max-retry-count: 5
retry-interval: 15000

defaults:
  tenant: "gorilla"
  authorization: "Basic bWlmb3M6cGFzc3dvcmQ="

channel:
  base-url: https://channel.sandbox.fynarfin.io
  endpoint: /channel/gsma/transaction

loan:
  base-url: https://fynams.sandbox.fynarfin.io
  endpoints:
    product-endpoint: /fineract-provider/api/v1/loanproducts
    account-endpoint: /fineract-provider/api/v1/loans
    approve-endpoint: /fineract-provider/api/v1/loans/{{loanAccId}}
    disburse-endpoint: /fineract-provider/api/v1/loans/{{loanAccId}}
    repayment-endpoint: /fineract-provider/api/v1/interoperation/transactions/{{loanAccId}}/loanrepayment
    accountid-endpoint: /fineract-provider/api/v1/loans/{{loanAccId}}

savings:
  base-url: https://fynams.sandbox.fynarfin.io
  endpoints:
    client-endpoint: /fineract-provider/api/v1/clients
    product-endpoint: /fineract-provider/api/v1/savingsproducts
    account-endpoint: /fineract-provider/api/v1/savingsaccounts
    approve-endpoint: /fineract-provider/api/v1/savingsaccounts/{{savingsAccId}}
    activate-endpoint: /fineract-provider/api/v1/savingsaccounts/{{savingsAccId}}
    deposit-endpoint: /fineract-provider/api/v1/savingsaccounts/{{savingsAccId}}/transactions
    interop-identifier-endpoint: /fineract-provider/api/v1/interoperation/parties/{{payer_identifierType}}/{{payer_identifier}}

mock-server:
  port: 53013

callback_url: ${CALLBACK_URL:localhost}

identity-account-mapper:
  contactpoint: "https://identity.sandbox.fynarfin.io"
  endpoints:
    register-beneficiary: /beneficiary
    add-payment-modality: /paymentModality
    update-payment-modality: /paymentModality
    account-lookup: /beneficiary
