operations-app:
  contactpoint: "https://ops-bk.sandbox.fynarfin.io"
  username: "mifos"
  password: "password"
  auth:
    enabled: false
  endpoints:
    auth: "/oauth/token"
    batch-summary: "/api/v1/batch"
    batch-details: "api/v1/batch/detail"
    batch-transaction: "/api/v1/batch/transactions"

    transfers: "/api/v1/transfers?size=1&page=0"
    transactionRequests: "/api/v1/transactionRequests"

bulk-processor:
  contactpoint: "https://bulk-connector.sandbox.fynarfin.io"
  endpoints:
    bulk-transactions: "/batchtransactions"

channel-connector:
  contactpoint: "https://channel.sandbox.fynarfin.io"
  endpoints:
    transfer: "/channel/transfer"
    gsma-p2p: "/channel/gsma/transfer"
    collection: "/channel/collection"

max-retry-count: 5
retry-interval: 15000

defaults:
  tenant: "gorilla"


channel:
  base-url: http://localhost:5008
  endpoint: "/api/v1/gsma/transaction"

loan:
  base-url: https://fynams.sandbox.fynarfin.io
  endpoints:
    product-endpoint: /fineract-provider/api/v1/loanproducts
    account-endpoint: /fineract-provider/api/v1/loans
    approve-endpoint: /fineract-provider/api/v1/loans/2
    disburse-endpoint: /fineract-provider/api/v1/loans/{{loanAccId}}
    repayment-endpoint: /api/v1/interoperation/transactions/{{loanAccId}}/loanrepayment

savings:
  base-url: https://fynams.sandbox.fynarfin.io
  endpoints:
    client-endpoint: /fineract-provider/api/v1/clients
    product-endpoint: /savingsproducts
    account-endpoint: /savingsaccounts
    approve-endpoint: /savingsaccounts/{{savingsAccId}}
    activate-endpoint: /savingsaccounts/{{savingsAccId}}
    deposit-endpoint: /savingsaccounts/{{savingsAccId}}/transactions
