operations-app:
  contactpoint: "https://ops-bk.sandbox.fynarfin.io"
  username: "mifos"
  password: "password"
  endpoints:
    auth: "/oauth/token"
    batch-summary: "/api/v1/batch"
    batch-details: "api/v1/batch/detail"
    batch-transaction: "/api/v1/batch/transactions"

bulk-processor:
  contactpoint: "https://bulk-connector.sandbox.fynarfin.io"
  endpoints:
    bulk-transactions: "/batchtransactions"

channel-connector:
  contactpoint: "https://channel.sandbox.fynarfin.io"
  endpoints:
    transfer: "/channel/transfer"
