version: 2.1

orbs:
  slack: circleci/slack@4.12.5
  helm: circleci/helm@2.0.1
  kubernetes: circleci/kubernetes@1.3
  mifos-orb: mifos/docker-image-availability-check-and-upgrade@1.0.2

executors:
  docker-executor:
    docker:
      - image: cimg/openjdk:17.0.0-node

jobs:
  build_and_publish:
    executor: docker-executor
    environment:
      JVM_OPTS: -Xmx512m
      TERM: dumb
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Tag Docker Image
          command: |
            TAG_NAME=${CIRCLE_BRANCH}
            ./gradlew bootJar
            docker build -t "openmf/ph-ee-integration-test:$TAG_NAME" .
      - run:
          name: Login to Docker Hub
          command: echo "$MIFOS_DOCKER_TOKEN" | docker login -u "$MIFOS_DOCKER_USER" --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker push "openmf/ph-ee-integration-test:$CIRCLE_BRANCH"

  test_chart_gov:
    docker:
      - image: cimg/openjdk:17.0.0-node
    steps:
      - checkout
      - run:
          name: Ngrok Setup
          command: |
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
      - run:
          name: Test Execution
          no_output_timeout: 30m
          command: |
            ngrok config add-authtoken $AUTH_TOKEN
            echo "web_addr: $LOCAL_PORT" >> /home/circleci/.config/ngrok/ngrok.yml
            ngrok http 53013 > /dev/null &
            echo -n "Extracting ngrok public url..."
            while [ -z "$NGROK_PUBLIC_URL" ]; do
              export NGROK_PUBLIC_URL=$(curl --silent --max-time 10 --connect-timeout 5 --show-error http://127.0.0.1:$LOCAL_PORT/api/tunnels | sed -nE 's/.*public_url":"https:..([^"]*).*/\1/p')
              sleep 1
            done
            export CALLBACK_URL="https://$NGROK_PUBLIC_URL"
            ./gradlew test -Dcucumber.filter.tags="@gov"
            pkill ngrok
      - store_test_results:
          path: build/test-results/test/TEST-org.mifos.integrationtest.TestRunner.xml
      - store_artifacts:
          path: build/test-results

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - push_docker_image:
          requires:
            - build
      # - test_chart_gov:
      #     requires:
      #       - push_docker_image


